# Generated by Django 4.2.2 on 2023-06-28 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataform_name', models.CharField(max_length=120, verbose_name='Plataform name')),
                ('plataform_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Plataform rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Property code')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Number of guests')),
                ('number_of_bathrooms', models.PositiveIntegerField(verbose_name='Number of bathrooms')),
                ('allowed_pet', models.BooleanField(verbose_name='Allowed pet')),
                ('cleaning_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'The value of cleaning cost can not be a negative number.')], verbose_name='Cleaning cost')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Activation date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Booking code')),
                ('check_in', models.DateField(verbose_name='Check-in date')),
                ('check_out', models.DateField(verbose_name='Check-out date')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Total price')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Number of guests')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='khanto.announcement', verbose_name='bookings')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='khanto.property'),
        ),
    ]
